version: '3.6'

networks:
  common:

services:
  nginx:
    hostname: nginx
    image: nginx:latest
    restart: unless-stopped
    networks:
      - common
    volumes:
      - ../:/app
      - ./nginx/log/:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - TZ=${TZ}

  fpm:
    working_dir: /app
    hostname: php-fpm
    image: ${FPM_IMAGE}
    restart: unless-stopped
    networks:
      - common
    volumes:
      - ../:/app
      - ./php/log/:/var/log/php7-fpm
      - ./php/app-config.ini:/usr/local/etc/php/conf.d/app-config.ini
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE}
      - XDEBUG_SESSION=${XDEBUG_SESSION}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      - TZ=${TZ}